/* Variaveis globais */
var WIREFRAME = false;
var SHADOW = false;
var BLACK = 0;
var WHITE = 1;
var FEEDBACK = 2;
var DEBUG = false;
var BOARD_SIZE = 100;
var PIECE_SIZE = 0.4;
var FLOOR_SIZE = 2000;
var COLS = 8;
var ROWS = 8;
var LOADING_BAR_SCALE = 0.3;